clientWebServer:
  clientWebServer:
    env:
      apiServerIp: "web-store-api-server-apiserverchart-service.default.svc.cluster.local"
      kafkaIp: "kafkachart-kafka-helm-b.default.svc.cluster.local"
    image:
      repository: oraharon/web-store-fe
      tag: "7"
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  type: ClusterIP
