apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webserverchart.fullname" . }}-client-web-server
  labels:
    app: client-web-server
  {{- include "webserverchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.clientWebServer.replicas }}
  selector:
    matchLabels:
      app: client-web-server
    {{- include "webserverchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: client-web-server
      {{- include "webserverchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: API_SERVER_IP
          value: {{ quote .Values.clientWebServer.clientWebServer.env.apiServerIp }}
        - name: KAFKA_IP
          value: {{ quote .Values.clientWebServer.clientWebServer.env.kafkaIp }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        # - name: KAFKA_PASSWORD
          # valueFrom:
            # secretKeyRef:
              # name: my-release-kafka-user-passwords
              # key: client-passwords
              
        image: {{ .Values.clientWebServer.clientWebServer.image.repository }}:{{ .Values.clientWebServer.clientWebServer.image.tag
          | default .Chart.AppVersion }}
        name: client-web-server
        ports:
        - containerPort: 8000
        resources: {}
