apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserverchart.fullname" . }}-service
  labels:
  {{- include "webserverchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: client-web-server
  {{- include "webserverchart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 }}